name: Publish The Forgotten to Itch.io

on:
 push:
  branches:
  - main
 pull_request:
  branches:
  - main

env:
  GODOT_VERSION: 4.2.1
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  EXPORT_NAME: TheForgotten

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: release-downloader
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "utopia-rise/fmod-gdextension"
          tag: "4.1.0-4.2.0"
          fileName: "addons.zip"
          extract: true
      - name: Windows Build
        run: |
          ls -lah addons/fmod/libs/windows
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: release-downloader
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "utopia-rise/fmod-gdextension"
          tag: "4.1.0-4.2.0"
          fileName: "addons.zip"
          extract: true  
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: release-downloader
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "utopia-rise/fmod-gdextension"
          tag: "4.1.0-4.2.0"
          fileName: "addons.zip"
          extract: true
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: build/mac

  itch:
    needs: [ export-windows, export-linux, export-mac ]
    name: Deploy to Itch
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
    - uses: actions/download-artifact@v4
    - name: Login To Butler
      run: |
        ./butler -V
        ./butler login
    
    - name: Push Windows Desktop to Itch
      run: ./butler push ./build/windows mindlessruff/the-forgotten:win
      #--userversion-file ./VERSION/VERSION.txt
    
    - name: Push macOS to Itch
      run: ./butler push ./build/mac mindlessruff/the-forgotten:mac
      #--userversion-file ./VERSION/VERSION.txt
    
    - name: Push Linux/X11 to Itch
      run: ./butler push ./build/linux mindlessruff/the-forgotten:linux
      #--userversion-file ./VERSION/VERSION.txt
          
